// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucdahnlndirmiecyptkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZGFobmxuZGlybWllY3lwdGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NjkxNjgsImV4cCI6MjA0OTQ0NTE2OH0.vbbbfoT1Dd7Fo3TxVQawkJuHF6-SuMN-gVM9A2os2Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);